Commit RC1

diff --git a/scripts/xdg-su b/scripts/xdg-su
--- a/scripts/xdg-su
+++ b/scripts/xdg-su
@@ -33,12 +33,39 @@
 #   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 #   OTHER DEALINGS IN THE SOFTWARE.
 #
+#   Permission is hereby granted, free of charge, to any person obtaining a
+#   copy of this software and associated documentation files (the "Software"),
+#   to deal in the Software without restriction, including without limitation
+#   the rights to use, copy, modify, merge, publish, distribute, sublicense,
+#   and/or sell copies of the Software, and to permit persons to whom the
+#   Software is furnished to do so, subject to the following conditions:
+#
+#   The above copyright notice and this permission notice shall be included
+#   in all copies or substantial portions of the Software.
+#
+#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
+#   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
+#   THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
+#   OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
+#   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
+#   OTHER DEALINGS IN THE SOFTWARE.
+#
 #---------------------------------------------
 
-distrib=`test -f /etc/lsb-release && 
+# Version of the application
+#---------------------------------------------
+VERSION="xdg-su 1.1rc1"
+
+#------------------------------------------------------------------------------
+# Find if  we' re on a *buntu distro
+# It is important to using sudo as default, without config
+#------------------------------------------------------------------------------
+
+distrib=$(test -f /etc/lsb-release && 
 	  cat /etc/lsb-release | 
 	  grep "DISTRIB_ID" | 
-	  sed 's/DISTRIB_ID=\([A-Za-z]\\)/\1/'`
+	  sed 's/DISTRIB_ID=\([A-Za-z]\\)/\1/')
 
 if [ -z $distrib ]; then
   distrib="Unknown"
@@ -51,6 +78,77 @@ fi
 manualpage()
 {
 cat << _MANUALPAGE
+Name
+
+   xdg-su - run a GUI program as root after prompting for the root password
+
+Synopsis
+
+   xdg-su -s [-x] [-u user] -c command
+
+   xdg-su { --help | --manual | --version }
+
+Description
+
+   xdg-su provides a graphical dialog that prompts the user for a password to
+   run command as user or as root if no user was specified.
+
+   xdg-su is for use inside a desktop session only.
+
+   xdg-su discards any stdout and stderr output from command.
+
+   You can create an empty "xdg-sudo" file in /etc to use sudo as default to
+   override default "su" mechanism and can avoid using "-s" option.
+
+Options
+
+   -u user
+           run command as user. The default is to run as root.
+
+   -s
+           run command via sudo
+
+   -x
+           run command via su. If sudo is default.
+
+   --help
+           Show command synopsis.
+
+   --manual
+           Show this manualpage.
+
+   --version
+           Show the xdg-utils version information.
+
+Exit Codes
+
+   An exit code of 0 indicates success while a non-zero exit code indicates
+   failure. The following failure codes can be returned:
+
+   1
+           Error in command line syntax.
+
+   2
+           One of the files passed on the command line did not exist.
+
+   3
+           A required tool could not be found.
+
+   4
+           The action failed.
+
+See Also
+
+   su(1)
+
+   sudo
+
+Examples
+
+ xdg-su -s -u root -c "/opt/shinythings/bin/install-GUI --install fast"
+
+   Runs the /opt/shinythings/bin/install-GUI command with root permissions
+   via sudo.
 Name
 
 xdg-su - run a GUI program as root after prompting for the root password
@@ -72,16 +170,27 @@ xdg-su discards any stdout and stderr output from command.
 
 Options
 
+-c command
+    to run command you must use this. Otherwise xdg-su won't work!
+    
 -u user
     run command as user. The default is to run as root.
+
 -s
-    run command via sudo. Ubuntu users don't need this option.
+    run command via sudo. Sudo must be properly configured to use this option.
+    *buntu Linux users don't need this option.
     You can create an empty "xdg-sudo" file in /etc to use sudo
     as default to override default and avoid using this option.
+
+-x
+   run command via su, if default is sudo.
+   
 --help
     Show command synopsis.
+    
 --manual
     Show this manualpage.
+    
 --version
     Show the xdg-utils version information.
 
@@ -119,12 +228,20 @@ _MANUALPAGE
 usage()
 {
 cat << _USAGE
+   xdg-su - run a GUI program as root after prompting for the root password
+
+Synopsis
+
+   xdg-su -s [-x] [-u user] -c command
+
+   xdg-su { --help | --manual | --version }
+
 xdg-su - run a GUI program as root after prompting for the root password
 Create an empty "xdg-sudo" file in /etc to use sudo as default.
 
 Synopsis
 
-xdg-su -s [-u user] -c command
+xdg-su -s [-x] [-u user] -c command
 
 xdg-su { --help | --manual | --version }
 
@@ -132,6 +249,225 @@ _USAGE
 }
 
 #@xdg-utils-common@
+
+#----------------------------------------------------------------------------
+#   Common utility functions included in all XDG wrapper scripts
+#----------------------------------------------------------------------------
+
+DEBUG()
+{
+  [ -z "${XDG_UTILS_DEBUG_LEVEL}" ] && return 0;
+  [ ${XDG_UTILS_DEBUG_LEVEL} -lt $1 ] && return 0;
+  shift
+  echo "$@" >&2
+}
+
+#-------------------------------------------------------------
+# Exit script on successfully completing the desired operation
+
+exit_success()
+{
+    if [ $# -gt 0 ]; then
+        echo "$@"
+        echo
+    fi
+
+    exit 0
+}
+
+
+#-----------------------------------------
+# Exit script on malformed arguments, not enough arguments
+# or missing required option.
+# prints usage information
+
+exit_failure_syntax()
+{
+    if [ $# -gt 0 ]; then
+        echo "xdg-su: $@" >&2
+        echo "Try 'xdg-su --help' for more information." >&2
+    else
+        usage
+        echo "Use 'man xdg-su' or 'xdg-su --manual' for additional info."
+    fi
+
+    exit 1
+}
+
+#-------------------------------------------------------------
+# Exit script on missing file specified on command line
+
+exit_failure_file_missing()
+{
+    if [ $# -gt 0 ]; then
+        echo "xdg-su: $@" >&2
+    fi
+
+    exit 2
+}
+
+#-------------------------------------------------------------
+# Exit script on failure to locate necessary tool applications
+
+exit_failure_operation_impossible()
+{
+    if [ $# -gt 0 ]; then
+        echo "xdg-su: $@" >&2
+    fi
+
+    exit 3
+}
+
+#-------------------------------------------------------------
+# Exit script on failure returned by a tool application
+
+exit_failure_operation_failed()
+{
+    if [ $# -gt 0 ]; then
+        echo "xdg-su: $@" >&2
+    fi
+
+    exit 4
+}
+
+#------------------------------------------------------------
+# Exit script on insufficient permission to read a specified file
+
+exit_failure_file_permission_read()
+{
+    if [ $# -gt 0 ]; then
+        echo "xdg-su: $@" >&2
+    fi
+
+    exit 5
+}
+
+#------------------------------------------------------------
+# Exit script on insufficient permission to read a specified file
+
+exit_failure_file_permission_write()
+{
+    if [ $# -gt 0 ]; then
+        echo "xdg-su: $@" >&2
+    fi
+
+    exit 6
+}
+
+check_input_file()
+{
+    if [ ! -e "$1" ]; then
+        exit_failure_file_missing "file '$1' does not exist"
+    fi
+    if [ ! -r "$1" ]; then
+        exit_failure_file_permission_read "no permission to read file '$1'"
+    fi
+}
+
+check_vendor_prefix()
+{
+    file_label="$2"
+    [ -n "$file_label" ] || file_label="filename"
+    file=`basename "$1"`
+    case "$file" in
+       [a-zA-Z]*-*)
+         return
+         ;;
+    esac
+
+    echo "xdg-su: $file_label '$file' does not have a proper vendor prefix" >&2
+    echo 'A vendor prefix consists of alpha characters ([a-zA-Z]) and is terminated' >&2
+    echo 'with a dash ("-"). An example '"$file_label"' is '"'example-$file'" >&2
+    echo "Use --novendor to override or 'xdg-su --manual' for additional info." >&2
+    exit 1
+}
+
+check_output_file()
+{
+    # if the file exists, check if it is writeable
+    # if it does not exists, check if we are allowed to write on the directory
+    if [ -e "$1" ]; then
+        if [ ! -w "$1" ]; then
+            exit_failure_file_permission_write "no permission to write to file '$1'"
+        fi
+    else
+        DIR=`dirname "$1"`
+        if [ ! -w "$DIR" -o ! -x "$DIR" ]; then
+            exit_failure_file_permission_write "no permission to create file '$1'"
+        fi
+    fi
+}
+
+#----------------------------------------
+# Checks for shared commands, e.g. --help
+
+check_common_commands()
+{
+    while [ $# -gt 0 ] ; do
+        parm="$1"
+        shift
+
+        case "$parm" in
+            --help)
+            usage
+            echo "Use 'man xdg-su' or 'xdg-su --manual' for additional info."
+            exit_success
+            ;;
+
+            --manual)
+            manualpage
+            exit_success
+            ;;
+
+            --version)
+            echo "xdg-su 1.0.2"
+            exit_success
+            ;;
+        esac
+    done
+}
+
+check_common_commands "$@"
+
+[ -z "${XDG_UTILS_DEBUG_LEVEL}" ] && unset XDG_UTILS_DEBUG_LEVEL;
+if [ ${XDG_UTILS_DEBUG_LEVEL-0} -lt 1 ]; then
+    # Be silent
+    xdg_redirect_output=" > /dev/null 2> /dev/null"
+else
+    # All output to stderr
+    xdg_redirect_output=" >&2"
+fi
+
+#--------------------------------------
+# Checks for known desktop environments
+# set variable DE to the desktop environments name, lowercase
+
+detectDE()
+{
+    if [ x"$KDE_FULL_SESSION" = x"true" ]; then DE=kde;
+    elif [ x"$GNOME_DESKTOP_SESSION_ID" != x"" ]; then DE=gnome;
+    elif `dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.gnome.SessionManager > /dev/null 2>&1` ; then DE=gnome;
+    elif xprop -root _DT_SAVE_MODE 2> /dev/null | grep ' = \"xfce4\"$' >/dev/null 2>&1; then DE=xfce;
+    elif [[ )ps aux) =~ ""lxsession"" ]]; then DE=lxde;
+    fi
+}
+
+#----------------------------------------------------------------------------
+# kfmclient exec/openURL can give bogus exit value in KDE <= 3.5.4
+# It also always returns 1 in KDE 3.4 and earlier
+# Simply return 0 in such case
+
+kfmclient_fix_exit_code()
+{
+    version=`kde${KDE_SESSION_VERSION}-config --version 2>/dev/null | grep KDE`
+    major=`echo $version | sed 's/KDE: \([0-9]\).*/\1/'`
+    minor=`echo $version | sed 's/KDE: [0-9]*\.\([0-9]\).*/\1/'`
+    release=`echo $version | sed 's/KDE: [0-9]*\.[0-9]*\.\([0-9]\).*/\1/'`
+    test "$major" -gt 3 && return $1
+    test "$minor" -gt 5 && return $1
+    test "$release" -gt 4 && return $1
+    return 0
+}
 
 #----------------------------------------------------------------------------
 #   Common utility functions included in all XDG wrapper scripts
@@ -248,7 +584,7 @@ check_input_file()
 
 check_vendor_prefix()
 {
-    file=`basename "$1"`
+    file=$(basename "$1")
     case "$file" in
        [a-zA-Z]*-*)
          return
@@ -271,7 +607,7 @@ check_output_file()
             exit_failure_file_permission_write "no permission to write to file '$1'"
         fi
     else
-        DIR=`dirname "$1"`
+        DIR=$(dirname "$1")
         if [ ! -w "$DIR" -o ! -x "$DIR" ]; then
             exit_failure_file_permission_write "no permission to create file '$1'"
         fi
@@ -300,7 +636,7 @@ check_common_commands()
             ;;
 
             --version)
-            echo "xdg-su 1.1beta2"
+            echo "$VERSION"
             exit_success
             ;;
         esac
@@ -316,6 +652,38 @@ else
     xdg_redirect_output=" >&2"
 fi
 
+#-------------------------------------------------------
+## Checks if user specified "sudo" usage
+#-------------------------------------------------------
+
+check_use_sudo()
+{
+    while [ $# -gt 0 ] ; do
+        parm="$1"
+        shift
+
+        case "$parm" in
+           -s)
+	    SUDO=$(which sudo 2>/dev/null)
+	    if [ -z "$SUDO" ] ; then
+	       exit_failure_syntax "Application 'sudo'  does not exist in your system. Please install it if you want use to..."
+	   else
+            distrib="Ubuntu"
+            fi
+            shift
+            ;;
+            
+           -x)
+	    distrib="Unknown"
+            shift
+            ;;
+        esac
+    done
+}
+
+check_use_sudo  "$@"
+
+
 #--------------------------------------
 # Checks for known desktop environments
 # set variable DE to the desktop environments name, lowercase
@@ -325,16 +693,21 @@ detectDE()
     if [ x"$KDE_FULL_SESSION" = x"true" ]; then DE=kde;
     elif [ x"$GNOME_DESKTOP_SESSION_ID" != x"" ]; then DE=gnome;
     elif xprop -root _DT_SAVE_MODE | grep ' = \"xfce4\"$' >/dev/null 2>&1; then DE=xfce;
-    elif [[ `ps aux` =~ ""lxsession"" ]]; then DE=lxde;
+    elif [[ )ps aux) =~ ""lxsession"" ]]; then DE=lxde;
     fi
 }
 
 #----------------------------------------------------------------------------
 
+#----------------------------------------------------------------------------------------
+# SUDO USAGE ON GNOME. 
+# If gksudo is present then use it. Otherwise default to gksu. 
+# If neither kdesudo nor kdesu is presnt use a terminal
+#----------------------------------------------------------------------------------------
 
 sudo_gnome()
 {
-    GSU=`which gksudo 2>/dev/null`
+    GSU=$(which gksudo 2>/dev/null)
     if [ $? -eq 0 ] ; then
         if [ -z "$user" ] ; then
             $GSU "$cmd"
@@ -352,63 +725,38 @@ sudo_gnome()
     fi
 }
 
+#----------------------------------------------------------------------------------------
+# SUDO USAGE ON KDE. 
+# If kdesudo is present then use it. Otherwise default to kdesu. 
+# If neither kdesudo nor kdesu is presnt use a terminal
+#----------------------------------------------------------------------------------------
 sudo_kde()
 {
-    GSU=`which kdesudo 2>/dev/null`
+    KDESUDO=$(which kdesudo 2>/dev/null)
     if [ x"$KDE_SESSION_VERSION" = x"4" ]; then
-        KDESU=`kde4-config --locate kdesu --path exe 2>/dev/null`
+        KDE_SU=$(kde4-config --locate kdesu --path exe 2>/dev/null)
     else
-        KDESU=`which kdesu 2>/dev/null`
+        KDE_SU=$(which kdesu 2>/dev/null)
     fi
-    if [ -z "$GSU" ] ; then
-      KSU=$KDESU
+    if [ -z "$KDESUDO" ] ; then
+      KDESU=$KDE_SU
     else
-      KSU=$GSU
+      KDESU=$KDESUDO
     fi
     if [ $? -eq 0 ] ; then
         if [ -z "$user" ] ; then
-            $KSU "$cmd"
-        else
-            $KSU -u "$user" "$cmd"
-        fi
-
-        if [ $? -eq 0 ]; then
-            exit_success
-        else
-            exit_failure_operation_failed
-        fi
-    else
-        su_generic
-    fi
-}
-
-su_kde()
-{
-    if [ x"$KDE_SESSION_VERSION" = x"4" ]; then
-        KDESU=`kde4-config --locate kdesu --path exe 2>/dev/null`
-    else
-        KDESU=`which kdesu 2>/dev/null`
-        if [ $? -ne 0 -a $distrib = "Ubuntu" ] ; then
-            KDESU=`which kdesudo 2>/dev/null`
-	else
-	    KDESU=`which kdesu 2>/dev/null`
-        fi
-    fi
-    if [ $? -eq 0 ] ; then
-        if [ -z "$user" ] ; then
-             if [ $distrib = "Ubuntu" ]; then
+             if [ $KDESU = "$KDESUDO"]; then
                   $KDESU "$cmd"
              else
                   $KDESU -c "$cmd"
              fi
         else
-             if [ $distrib = "Ubuntu" ]; then
-                  $KDESU -u "$user" "$cmd"
+             if [ $KDESU = "$KDESUDO" ]; then
+                  $KDESUDO -u "$user" "$cmd"
              else
-                  $KDESU -u "$user" -c "$cmd"
+                  $KDESUDO -u "$user" -c "$cmd"
              fi
         fi
-
         if [ $? -eq 0 ]; then
             exit_success
         else
@@ -419,13 +767,58 @@ su_kde()
     fi
 }
 
+#----------------------------------------------------------------------------------------
+# Su usage on KDE. 
+#----------------------------------------------------------------------------------------
+
+su_kde()
+{
+    KDESUDO=$(which kdesudo 2>/dev/null)
+   if [ x"$KDE_SESSION_VERSION" = x"4" ]; then
+        KDE_SU=$(kde4-config --locate kdesu --path exe 2>/dev/null)
+    else
+        KDE_SU=$(which kdesu 2>/dev/null)
+        if  [ $? -ne 0 -a $distrib = "Ubuntu" ]  ; then
+        KDESU=$KDE_SUDO
+        else
+        KDESU=$KDE_SU
+        fi
+    fi
+
+    if [ $? -eq 0 ] ; then
+        if [ -z "$user" ] ; then
+             if [ $KDESU = "$KDESUDO"]; then
+                  $KDESU "$cmd"
+             else
+                  $KDESU -c "$cmd"
+             fi
+        else
+             if [ $KDESU = "$KDESUDO" ]; then
+                  $KDESUDO -u "$user" "$cmd"
+             else
+                  $KDESUDO -u "$user" -c "$cmd"
+             fi
+        fi
+        if [ $? -eq 0 ]; then
+            exit_success
+        else
+            exit_failure_operation_failed
+        fi
+    else
+        su_generic
+    fi
+}
+
+#----------------------------------------------------------------------------------------
+# Su usage on GNOME 
+#----------------------------------------------------------------------------------------
 su_gnome()
 {
-    GSU=`which gnomesu 2>/dev/null`
+    GSU=$(which gnomesu 2>/dev/null)
     if [ $? -ne 0 ] ; then
-    	GSU=`which gksu 2>/dev/null`
+    	GSU=$(which gksu 2>/dev/null)
     else
-        GSU=`which xsu 2>/dev/null`
+        GSU=$(which xsu 2>/dev/null)
     fi
     if [ $? -eq 0 ] ; then
         if [ -z "$user" ] ; then
@@ -466,13 +859,14 @@ su_generic()
     
     QUOTE=1
     TERMINAL=""
-    [ -z "$TERMINAL" ] && TERMINAL=`which xterm 2> /dev/null` && QUOTE=0
-    [ -z "$TERMINAL" ] && TERMINAL=`which gnome-terminal 2> /dev/null`
-    #[ -z "$TERMINAL" ] && TERMINAL=`which konsole 2> /dev/null`
-    [ -z "$TERMINAL" ] && TERMINAL=`which aterm 2> /dev/null` && QUOTE=0
-    [ -z "$TERMINAL" ] && TERMINAL=`which Eterm 2> /dev/null` 
-    [ -z "$TERMINAL" ] && TERMINAL=`which kterm 2> /dev/null` && QUOTE=0
-    [ -z "$TERMINAL" ] && TERMINAL=`which lxterminal 2> /dev/null`
+    [ -z "$TERMINAL" ] && TERMINAL=$(which xterm 2> /dev/null) && QUOTE=0
+    [ -z "$TERMINAL" ] && TERMINAL=$(which gnome-terminal 2> /dev/null)
+    # Won't use konsole, it simply won't work :(
+    #[ -z "$TERMINAL" ] && TERMINAL=$(which konsole 2> /dev/null)
+    [ -z "$TERMINAL" ] && TERMINAL=$(which aterm 2> /dev/null) && QUOTE=0
+    [ -z "$TERMINAL" ] && TERMINAL=$(which Eterm 2> /dev/null) 
+    [ -z "$TERMINAL" ] && TERMINAL=$(which kterm 2> /dev/null) && QUOTE=0
+    [ -z "$TERMINAL" ] && TERMINAL=$(which lxterminal 2> /dev/null)
 
     if [ $distrib = "Ubuntu" ]; then
 	 if [ $QUOTE -eq 1 ]; then
@@ -520,9 +914,6 @@ while [ $# -gt 0 ] ; do
         fi
         cmd="$1"
         shift
-        ;;
-      -s)
-        distrib="Ubuntu"
         ;;
 
       -*)
