- Add BeeSu support (experimental) - Add GKsu-Polkit support (experimental) - Add MATE Desktop support (experimental) - Fix sudo usage in commandline mode

diff --git a/scripts/xdg-su.in b/scripts/xdg-su.in
--- a/scripts/xdg-su.in
+++ b/scripts/xdg-su.in
@@ -353,9 +353,10 @@ detectDE()
   if [ x$DISPLAY != x ] ; then
       if [ x"$KDE_FULL_SESSION" = x"true" ]; then DE=kde;
       elif [ x"$GNOME_DESKTOP_SESSION_ID" != x"" ]; then DE=gnome;
-      elif `dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.gnome.SessionManager > /dev/null 2>&1` ; then DE=gnome;
+      elif $(dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.gnome.SessionManager > /dev/null 2>&1) ; then DE=gnome;
       elif xprop -root _DT_SAVE_MODE 2> /dev/null | grep ' = \"xfce4\"$' >/dev/null 2>&1; then DE=xfce;
       elif [[ $(ps aux) =~ ""lxsession"" ]]; then DE=lxde;
+      elif [[ $(ps aux) =~ ""mate-session"" ]]; then DE=mate;
       fi
   else
       exit_failure_operation_impossible "FATAL ERROR: You' re not running X server.  No use of graphical environment. Exiting ..." 
@@ -369,7 +370,7 @@ detectDE()
 
 kfmclient_fix_exit_code()
 {
-    version=`kde${KDE_SESSION_VERSION}-config --version 2>/dev/null | grep KDE`
+    version=$(kde${KDE_SESSION_VERSION}-config --version 2>/dev/null | grep KDE)
     major=`echo $version | sed 's/KDE: \([0-9]\).*/\1/'`
     minor=`echo $version | sed 's/KDE: [0-9]*\.\([0-9]\).*/\1/'`
     release=`echo $version | sed 's/KDE: [0-9]*\.[0-9]*\.\([0-9]\).*/\1/'`
@@ -520,9 +521,42 @@ su_ktsuss()
             exit_failure_operation_failed
         fi
     else
-        su_generic
+        echo "Ktsuss not found; attempting to use BeeSu" && su_beesu
     fi
 }
+
+su_gksu_polkit()
+{
+
+    SU_GKSU_POLKIT=$(which gksu-polkit 2> /dev/null)
+    if [ $? -eq 0 ] ; then
+        $SU_GKSU_POLKIT $cmd
+        if [ $? -eq 0 ]; then
+            exit_success
+        else
+            exit_failure_operation_failed
+        fi
+    else
+        echo "GKsu-Polkit not found attempting to use command line" && su_generic
+    fi
+}
+
+su_beesu()
+{
+
+    BEESU=$(which beesu 2> /dev/null)
+    if [ $? -eq 0 ] ; then
+        $BEESU "$cmd"
+        if [ $? -eq 0 ]; then
+            exit_success
+        else
+            exit_failure_operation_failed
+        fi
+    else
+        echo "BeeSu not found attepting to use GKsu-polkit" && su_gksu_polkit
+    fi
+}
+
 
 su_generic()
 {
@@ -537,15 +571,16 @@ su_generic()
     [ -z "$TERMINAL" ] && TERMINAL=$(which kterm 2> /dev/null ) && QUOTE=0
     [ -z "$TERMINAL" ] && TERMINAL=$(which lxterminal 2> /dev/null)
     [ -z "$TERMINAL" ] && TERMINAL=$(which Terminal 2> /dev/null) && QUOTE=0
+    [ -z "$TERMINAL" ] && TERMINAL=$(which mate-terminal 2> /dev/null)
 
     if [ $distrib = "Ubuntu" ]; then
 	 if [ $QUOTE -eq 1 ]; then
-              $TERMINAL -e "sudo $cmd"
+              $TERMINAL -e "sudo -H $cmd"
 	 else
 	    if  [ $TERMINAL = $(which Terminal 2> /dev/null) ]; then
-	      $TERMINAL -H -x sudo "$cmd"
+	      $TERMINAL -H -x sudo -H "$cmd"
 	   else
-	      $TERMINAL -e sudo "$cmd"
+	      $TERMINAL -e sudo -H "$cmd"
 	   fi
 	 fi
     else
@@ -604,7 +639,7 @@ case "$DE" in
         fi
     ;;
 
-    gnome*|lxde*|xfce)
+    gnome*|lxde*|xfce|mate*)
         if [ $distrib = "Ubuntu" ]; then
             sudo_gnome
         else
